### ISSUE TITLE
Script returning incorrect responses

### ISSUE THREAD

**Issue by bjsmith16** [GoogleChromeLabs/privacy-sandbox-explainer-updates#8]
For the last couple of weeks the script is returning incorrect responses - explainer links that dont have any new commits. I have attached a photo of the commands in my terminal, the script responses, and the explainer page showing no updates. 
<img width="1504" alt="Screen Shot 2022-12-12 at 12 32 30 PM" src="https://user-images.githubusercontent.com/114695190/207138041-52858bb4-992a-4b79-bcdf-9ae5fdcf409e.png">
<img width="1495" alt="Screen Shot 2022-12-12 at 12 33 07 PM" src="https://user-images.githubusercontent.com/114695190/207138060-8cc33f7a-d65e-4ad5-8a64-639ec666fcb7.png">

**Comment by miketaylr** [comment]
Sorry for the delay @bjsmith16! I think the issue here is an invalid GitHub token - I'm able to reproduce the issue w/ an expired token:

![Screenshot 2023-01-19 at 5 29 55 PM](https://user-images.githubusercontent.com/67283/213576696-625b1f29-704b-4425-a7f2-12ca9439a5f3.png)

But if I update my `.env` file with a valid token, I get expected results:

![Screenshot 2023-01-19 at 5 34 00 PM](https://user-images.githubusercontent.com/67283/213577405-ab705523-b0c1-49b0-b791-b88b57747f75.png)

@bjsmith16 can you verify that your token has not expired?

**Comment by bjsmith16** [comment]
That was definitely the issue. I put in a new token that doesnt expire and got the expected results. Thanks for looking into this, @miketaylr
